"use strict";
let Myname = document.getElementById('name');
let jobTitle = document.getElementById('jobtitle');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let address = document.getElementById('address');
let passingYear1 = document.getElementById('passing year1');
let degree1 = document.getElementById('degree1');
let institute1 = document.getElementById('institute1');
let passingYear2 = document.getElementById('passing year2');
let degree2 = document.getElementById('degree2');
let institute2 = document.getElementById('institute2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let language1 = document.getElementById('language1');
let language2 = document.getElementById('language2');
let startyear = document.getElementById('startyear');
let endyear = document.getElementById('endyear');
let company = document.getElementById('company');
let companylocation = document.getElementById('companylocation');
let jobtitle2 = document.getElementById('jobtitle2');
let achivements1 = document.getElementById('achivements1');
let achivements2 = document.getElementById('achivements2');
let achivements3 = document.getElementById('achivements3');
let profilepic = document.getElementById('profilepic');
let submitbtn = document.getElementById('submitbtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem('name', Myname.value);
    localStorage.setItem('jobtitle', jobTitle.value);
    localStorage.setItem('phone', phone.value);
    localStorage.setItem('email', email.value);
    localStorage.setItem('address', address.value);
    localStorage.setItem('passing year1', passingYear1.value);
    localStorage.setItem('degree1', degree1.value);
    localStorage.setItem('institute1', institute1.value);
    localStorage.setItem('passing year2', passingYear2.value);
    localStorage.setItem('degree2', degree2.value);
    localStorage.setItem('institute2', institute2.value);
    localStorage.setItem('skill1', skill1.value);
    localStorage.setItem('skill2', skill2.value);
    localStorage.setItem('skill3', skill3.value);
    localStorage.setItem('language1', language1.value);
    localStorage.setItem('language2', language2.value);
    localStorage.setItem('startyear', startyear.value);
    localStorage.setItem('endyear', endyear.value);
    localStorage.setItem('company', company.value);
    localStorage.setItem('companylocation', companylocation.value);
    localStorage.setItem('jobtitle2', jobtitle2.value);
    localStorage.setItem('achivements1', achivements1.value);
    localStorage.setItem('achivements2', achivements2.value);
    localStorage.setItem('achivements3', achivements3.value);
    if (profilepic.files && profilepic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener('load', () => {
            let textImg = reader.result;
            localStorage.setItem('profilepic', textImg);
        });
        reader.readAsDataURL(profilepic.files[0]);
    }
    window.location.href = "./milestones/resume.html";
});
